'use strict';

/**
 * CoderAgent
 *
 * Responsibility: TestPlan → executable Playwright spec files + optional Gherkin features.
 *
 * Input:  { testPlan, ticketId, mode, generateFeatures?: boolean }
 * Output: { specFiles: [{path, content, scenarioIds}], featureFiles: [{path, content}], outputDir }
 *
 * Generated tests:
 *  - Use BasePage pattern from existing repo
 *  - Use existing envConfig for base URLs
 *  - Group by type (positive / negative / edge) → one spec file per type
 *  - Each scenario → one test() block with proper assertions
 *  - All selectors from env vars / data-testid (no hardcoding)
 *  - Optional: mirror structure as Gherkin .feature file
 */

const path   = require('path');
const fs     = require('fs');
const AgentBase = require('../core/agent-base');

const OUT_BASE = path.resolve(__dirname, '../../orchestration/generated');

class CoderAgent extends AgentBase {
  constructor(opts = {}) {
    super('CoderAgent', opts);
    this.generateFeatures = opts.generateFeatures !== false;
  }

  async execute(input) {
    const { testPlan, ticketId, mode } = input;
    if (!testPlan) throw new Error('testPlan is required');

    const testsDir    = path.join(OUT_BASE, 'tests',    ticketId);
    const featuresDir = path.join(OUT_BASE, 'features', ticketId);
    fs.mkdirSync(testsDir,    { recursive: true });
    if (this.generateFeatures) fs.mkdirSync(featuresDir, { recursive: true });

    const byType = { positive: [], negative: [], edge: [] };
    for (const sc of testPlan.scenarios) {
      (byType[sc.type] || byType['edge']).push(sc);
    }

    const specFiles    = [];
    const featureFiles = [];

    for (const [type, scenarios] of Object.entries(byType)) {
      if (!scenarios.length) continue;

      // ── Playwright spec ──────────────────────────────────────────────────
      const specContent  = this._buildSpec(ticketId, testPlan, type, scenarios, mode);
      const specFileName = `${ticketId}-${type}.spec.js`;
      const specPath     = path.join(testsDir, specFileName);
      if (!this.dryRun) fs.writeFileSync(specPath, specContent, 'utf8');
      specFiles.push({
        path:        specPath,
        relativePath: path.relative(process.cwd(), specPath),
        scenarioIds: scenarios.map(s => s.id),
        type
      });

      // ── Gherkin feature ──────────────────────────────────────────────────
      if (this.generateFeatures) {
        const featureContent  = this._buildFeature(ticketId, testPlan, type, scenarios);
        const featureFileName = `${ticketId}-${type}.feature`;
        const featurePath     = path.join(featuresDir, featureFileName);
        if (!this.dryRun) fs.writeFileSync(featurePath, featureContent, 'utf8');
        featureFiles.push({
          path:        featurePath,
          relativePath: path.relative(process.cwd(), featurePath),
          type
        });
      }
    }

    this.log.info('Code generation complete', {
      specFiles:    specFiles.length,
      featureFiles: featureFiles.length,
      outputDir:    OUT_BASE
    });

    return { ticketId, specFiles, featureFiles, outputDir: OUT_BASE };
  }

  // ── Spec builder ────────────────────────────────────────────────────────────

  _buildSpec(ticketId, testPlan, type, scenarios, mode) {
    const isDryRun = mode === 'mock';
    const header = `// AUTO-GENERATED by CoderAgent — ${new Date().toISOString()}
// Ticket: ${ticketId}  |  Type: ${type.toUpperCase()}
// DO NOT EDIT manually — re-run orchestration to regenerate.
//
// This file uses the existing Playwright framework conventions:
//   - BasePage helpers (click, fill, getText, waitForSelector)
//   - envConfig for base URLs
//   - All credentials from environment variables only

'use strict';

const { test, expect } = require('@playwright/test');
const path = require('path');

// Load env config from existing framework
let envConfig;
try {
  envConfig = require(path.resolve(__dirname, '../../../config/env.config'));
} catch {
  envConfig = { baseUrl: process.env.BASE_URL || 'http://localhost:3000' };
}

const BASE_URL = envConfig.baseUrl || process.env.BASE_URL || 'http://localhost:3000';

test.describe('${ticketId} — ${testPlan.title} [${type.toUpperCase()}]', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(BASE_URL, { waitUntil: 'domcontentloaded' });
  });
`;

    const testBlocks = scenarios.map(sc => this._buildTestBlock(sc, isDryRun));

    return header + '\n' + testBlocks.join('\n\n') + '\n});\n';
  }

  _buildTestBlock(scenario, isDryRun) {
    const tags    = scenario.tags.map(t => `@${t}`).join(' ');
    const timeout = scenario.type === 'edge' ? 45000 : 30000;
    const lines   = [];

    lines.push(`  // ${scenario.id} | Priority: ${scenario.priority} | ${tags}`);
    lines.push(`  test('${this._escapeStr(scenario.title)}', async ({ page }) => {`);
    lines.push(`    test.setTimeout(${timeout});`);
    lines.push('');

    if (isDryRun) {
      lines.push(`    // DRY-RUN mode — assertions skipped, structure validated only`);
      lines.push(`    // Steps: ${scenario.steps.join(' | ')}`);
      lines.push(`    // Expected: ${scenario.expectedOutcome}`);
      lines.push(`    console.log('[DRY-RUN] ${scenario.id}: ${this._escapeStr(scenario.title)}');`);
    } else {
      // Emit real step implementations based on step text patterns
      for (const step of scenario.steps) {
        lines.push(`    // ${step}`);
        lines.push(this._stepToCode(step, scenario));
      }
      lines.push('');
      lines.push(this._buildAssertion(scenario));
    }

    // Attach test data as comment for traceability
    if (Object.keys(scenario.testData).length > 0) {
      lines.push('');
      lines.push(`    // Test data: ${JSON.stringify(scenario.testData)}`);
    }

    lines.push('  });');
    return lines.join('\n');
  }

  _stepToCode(step, scenario) {
    const s = step.toLowerCase();
    const parts = [];

    if (s.includes('navigate') || s.includes('navigates to')) {
      parts.push(`    await page.waitForLoadState('domcontentloaded');`);
    }
    if (s.includes('fill') || s.includes('enter') || s.includes('input')) {
      if (scenario.testData.email) {
        parts.push(`    await page.fill('[data-testid="email-input"], input[type="email"], #email', ${JSON.stringify(scenario.testData.email || '')});`);
      }
      if (scenario.testData.password) {
        parts.push(`    await page.fill('[data-testid="password-input"], input[type="password"], #password', process.env.TEST_USER_PASSWORD || ${JSON.stringify(scenario.testData.password || '')});`);
      }
      if (scenario.testData.otp) {
        parts.push(`    await page.fill('[data-testid="otp-input"], input[name="otp"], #otp', ${JSON.stringify(scenario.testData.otp || '')});`);
      }
    }
    if (s.includes('click') || s.includes('submit')) {
      parts.push(`    await page.click('[data-testid="submit-btn"], button[type="submit"], [type="submit"]');`);
    }
    if (s.includes('checkbox') || s.includes('remember')) {
      parts.push(`    await page.check('[data-testid="remember-me"], input[name="rememberMe"], #rememberMe');`);
    }
    if (s.includes('wait') || s.includes('redirect')) {
      parts.push(`    await page.waitForNavigation({ waitUntil: 'networkidle' }).catch(() => {});`);
    }
    return parts.length ? parts.join('\n') : `    // TODO: implement step: ${step}`;
  }

  _buildAssertion(scenario) {
    // Safely handle expectedOutcome (may be string, array, object, or null)
    let out = scenario.expectedOutcome;
    if (!out) out = '';
    if (typeof out === 'object') out = JSON.stringify(out);
    out = String(out).toLowerCase();
    const lines = [];

    if (out.includes('dashboard')) {
      lines.push(`    await expect(page).toHaveURL(/dashboard/i);`);
      lines.push(`    await expect(page.locator('[data-testid="dashboard-heading"], h1')).toBeVisible();`);
    } else if (out.includes('error') || out.includes('message') || out.includes('invalid')) {
      lines.push(`    await expect(page.locator('[data-testid="error-message"], [role="alert"], .error')).toBeVisible();`);
      lines.push(`    await expect(page.locator('[data-testid="error-message"], [role="alert"]')).not.toBeEmpty();`);
    } else if (out.includes('locked')) {
      lines.push(`    await expect(page.locator('[data-testid="account-locked"], [role="alert"]')).toBeVisible();`);
    } else if (out.includes('otp') || out.includes('verification')) {
      lines.push(`    await expect(page.locator('[data-testid="otp-step"], [data-testid="otp-input"]')).toBeVisible();`);
    } else if (out.includes('redirect') || out.includes('page')) {
      lines.push(`    await expect(page).not.toHaveURL(/login/i);`);
    } else {
      lines.push(`    // TODO: add explicit assertion for: ${scenario.expectedOutcome}`);
      lines.push(`    await expect(page.locator('body')).toBeVisible();`);
    }

    return lines.join('\n');
  }

  // ── Feature builder ─────────────────────────────────────────────────────────

  _buildFeature(ticketId, testPlan, type, scenarios) {
    const lines = [];
    lines.push(`# AUTO-GENERATED by CoderAgent — ${new Date().toISOString()}`);
    lines.push(`# Ticket: ${ticketId}  |  Type: ${type.toUpperCase()}`);
    lines.push('');
    lines.push(`Feature: ${ticketId} — ${testPlan.title} [${type.toUpperCase()}]`);
    lines.push(`  As a user`);
    lines.push(`  I want the ${testPlan.domain} feature to work correctly`);
    lines.push(`  So that I can complete my workflow without errors`);
    lines.push('');

    for (const sc of scenarios) {
      const tags = sc.tags.map(t => `@${t}`).join(' ');
      lines.push(`  ${tags}`);
      lines.push(`  Scenario: ${sc.title}`);
      for (const step of sc.steps) {
        // Classify step into Given/When/Then/And
        const prefix = this._gherkinPrefix(step);
        lines.push(`    ${prefix} ${step.replace(/^(given|when|then|and)\s+/i, '')}`);
      }
      if (Object.keys(sc.testData).length > 0) {
        lines.push(`    # Test data: ${JSON.stringify(sc.testData)}`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  _gherkinPrefix(step) {
    const s = step.toLowerCase().trim();
    if (s.startsWith('given')) return 'Given';
    if (s.startsWith('when'))  return 'When';
    if (s.startsWith('then'))  return 'Then';
    if (s.startsWith('and'))   return 'And';
    return 'And';
  }

  _escapeStr(s) {
    return s.replace(/'/g, "\\'").replace(/\n/g, ' ');
  }
}

module.exports = CoderAgent;
